# Stage 0: compile angular frontend
FROM node:14 as build
WORKDIR /app
COPY . . 
RUN npm install
RUN npm run build

# Stage 1: serve app with nginx server
FROM nginx:latest
COPY --from=build /app/dist/rover-ui  /usr/share/nginx/html
EXPOSE 80